#:schema https://mise.jdx.dev/schema/mise.json

[bootstrap.secrets]
itm_llm_gw_key = "ITM_LLM_GW_KEY"

[bootstrap.services]
mise-history = { builtin = "history-watch" }

[dotfiles]
"~/.config/bat" = { mode = "track" }
"~/.config/btop" = { mode = "track" }

"~/.config/fnox/config.toml" = { mode = "track" }
"~/.config/mise/config.toml" = { mode = "track" }
"~/.config/mise/settings.toml" = { mode = "track" }
"~/.config/mise/templates/zshenv.tmpl" = { mode = "track" }
"~/.config/nvim" = { mode = "track" }
"~/.config/starship.toml" = { mode = "track" }
"~/.config/zellij" = { mode = "track" }

"~/.zshenv" = { source = "templates/zshenv.tmpl", mode = "template", permissions = "0600" }
"~/.zshrc" = { mode = "track" }

[bootstrap.mise_shell_activate]
zsh = true

[tools]
usage = "latest"
bitwarden = "latest"
fnox = "latest"
age = "latest"
btop = "latest"
opencode = "latest"
bun = "latest"
node = "lts-krypton"
dotnet = "10"
terraform = "latest"
rust = "stable"
starship = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
bat = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
"npm:codeburn" = "latest"

[settings]
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true
legacy_version_file_disable_tools = []

# configure `mise install` to always keep the downloaded archive
always_keep_download = false
always_keep_install = false

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/issues/128)
plugin_autoupdate_last_check_duration = '1 week'

# config files with these prefixes will be trusted by default
trusted_config_paths = []

verbose = false
asdf_compat = false
jobs = 4
raw = false
yes = false

not_found_auto_install = true
output = "prefix"
paranoid = false

disable_tools = []
